#!/usr/bin/env bash
#Task 12
input="/etc/passwd"

while IFS= read -r username password uid gid userdinfo homedir commandshell
do
        echo "The user $username is part of the $gid gang, lives in $homedir and rides $commandshell. $uid's place is protected by the passcode $password, more info about the user here: $useridinfo"
done < "$input"
