#!/usr/bin/env bash
#Task 9
FILE="school"
if [ -e $FILE ]
        then 
                echo "school file exists"
        if [ -s $FILE ]     
		then
			echo "school file is empty"
		elif 
			echo "school is a regular file"
		else
			echo "school file is not empty"
	fi                

	else
                echo "schoo file does not exist"
fi
