#!/usr/bin/env bash
# Multiple traps
echo $$ > /var/run/myscript.pid
trap "echo 'I heat the kill command'; rm -f /var/run/myscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -f /var/run/myscript.pid; exit" SIGQUIT
while :
do
	echo "To infinity and beyond"
	sleep 2
done
