#!/usr/bin/env bash
# Multiple traps

trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command'" SIGTERM
trap "sudo rm /var/run/myscript.pid" SIGQUIT
echo $$ >> /var/run/myscript.pid
while true
do
	echo 'To infinity and beyond'
done
