#!/usr/bin/env bash
# Multiple traps
rmfile()
{
	rm -f /van/run/myscript.pid
}
trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command'; rmfile" SIGTERM
trap "echo 'I hate the kill command'; rm -fr /var/run/myscript.pid" SIGQUIT
echo $$ > /var/run/myscript.pid
while true
do
	echo 'To infinity and beyond'
	sleep 2
done
